# Generated by Django 2.1.3 on 2018-11-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
